### ISSUE TITLE
private key is unreadable

### ISSUE THREAD

**Issue by kn0sys** [kn0sys/j4-i2p-rs#2]
see [cookbook.md](https://github.com/kn0sys/j4-i2p-rs/blob/main/cookbook.md)

```bash
[1]: Private key file does not exist or is not readable: sk.e57206752286e79a6dd072cdccc1a663.dat
org.astonbitecode.j4rs.errors.InstantiationException: Cannot create instance of net.i2p.i2ptunnel.I2PTunnel
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.instantiate(NativeInstantiationImpl.java:47)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.createInstance(NativeInstantiationImpl.java:101)
	at org.astonbitecode.j4rs.api.instantiation.NativeInstantiationImpl.instantiate(NativeInstantiationImpl.java:44)
Caused by: java.lang.IllegalArgumentException: [1]: Cannot open private key file sk.e57206752286e79a6dd072cdccc1a663.dat
	at net.i2p.i2ptunnel.I2PTunnel.runServer(I2PTunnel.java:654)
	at net.i2p.i2ptunnel.I2PTunnel.runCommand(I2PTunnel.java:435)
	at net.i2p.i2ptunnel.I2PTunnel.<init>(I2PTunnel.java:278)
	at net.i2p.i2ptunnel.I2PTunnel.<init>(I2PTunnel.java:180)
	at net.i2p.i2ptunnel.I2PTunnel.<init>(I2PTunnel.java:171)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 4 more
```

**Comment by kn0sys** [comment]
Needed to use absolute path not relative.
